name: Java CI with Maven

on:
  push:
    paths:
      - '**'
    branches:
      - main
  pull_request:
    paths:
      - '**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/demo/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Print Current Directory
        run: pwd

      - name: List Files in Current Directory
        run: ls -la

      - name: Run XMLGeneratorServiceTest
        run: |
          cd backend/demo
          pwd
          ls -la
          mvn -B -f pom.xml -Dtest=XMLGeneratorServiceTest test
